export const FETCHORDERMETADATA = "FETCHORDERMETADATA"
export const SEARCHDATA ="SEARCHDATA"
export const SHOWSKELETON = "SHOWSKELETON"
export const TOGGLEFLAG = "TOGGLEFLAG"
export const FLAGVALUE ="FLAGVALUE"


